version: '3.8'

services:
  # Your Go API
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017

  # Your MongoDB Database
  db:
    image: mongo:latest
    container_name: mongo-nails-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: